### ISSUE TITLE
Documentação do OPAC Schema.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac_schema#2]
Não existe documentação, devemos criar uma documentação seguindo os modelos que conhecemos.

**Comment by jfunez** [comment]
Atualmente temos documentados os modelos com json schema para cada modelo (``opac_schema/docs/v1/<model>/schema.json``).
Devemos aprimorar a atualização desses schemas para garantir que não esteja desatualizado, mas isso sera feito em outro issue.
