### ISSUE TITLE
Pages - permitir que slug_name seja editável

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac_schema#76]
O slug_name está sempre sendo gerado a partir do name.
Melhor que o usuário possa informar o valor para slug_name.
No entanto, o valor de slug_name, também deve ser "slugified", ou seja, se o usuário informar "Página 1" como slug_name, convertê-lo para "pagina-1".

**Comment by cesarbruschetta** [comment]
PR #80 Melhora essa funcionalidade
